name: "Aqua registry login + run image scanner"
description: "Logs into private Aqua Docker registry, runs the image scanner, and uploads scan results"

inputs:
  registry:
    description: "Scanner Registry hostname (e.g. registry.aquasec.com)"
    required: true
  username:
    description: "Scanner Registry username"
    required: true
  password:
    description: "Scanner Registry password"
    required: true
  scanner_image:
    description: "Scanner Image name (e.g. scanner)"
    required: true
  tag:
    description: "Scanner Image tag"
    required: false
    default: "10"
  run_args:
    description: "Extra args passed to docker run (e.g. -e A=B -v ...)"
    required: false
    default: ""
  scan_args:
    description: "Command appended to docker run"
    required: false
    default: ""

  # New: upload configuration
  artifact_name:
    description: "Name of the uploaded artifact"
    required: false
    default: "Aqua Scan Report"
  report_paths:
    description: "Paths to scan reports (multiline allowed)"
    required: false
    default: |
      /tmp/out.html
      /tmp/out.json
  if_no_files_found:
    description: "upload-artifact behavior when no files found: warn|error|ignore"
    required: false
    default: "warn"

  logout:
    description: "Whether to docker logout after running"
    required: false
    default: "true"

  # New: whether to fail the action if the scan failed (after uploading artifacts)
  fail_on_scan_error:
    description: "Fail the action if scanner exits non-zero (after uploading)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: "${{ inputs.registry }}"
        username: "${{ inputs.username }}"
        password: "${{ inputs.password }}"

    - name: Pull image
      shell: bash
      run: |
        set -euo pipefail
        IMAGE="${{ inputs.registry }}/${{ inputs.scanner_image }}:${{ inputs.tag }}"
        docker pull "$IMAGE"

    # Run scan but don't hard-fail the composite yet; record exit code
    - name: Run container (capture exit code)
      id: scan
      shell: bash
      run: |
        set -euo pipefail
        IMAGE="${{ inputs.registry }}/${{ inputs.scanner_image }}:${{ inputs.tag }}"

        set +e
        # shellcheck disable=SC2086
        docker run --rm ${{ inputs.run_args }} "$IMAGE" scan ${{ inputs.scan_args }}
        rc=$?
        set -e

        echo "exit_code=$rc" >> "$GITHUB_OUTPUT"

    # Always upload results, even if scan step failed
    - name: Upload scan results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.report_paths }}
        if-no-files-found: ${{ inputs.if_no_files_found }}

    - name: Logout
      if: ${{ always() && inputs.logout == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        docker logout "${{ inputs.registry }}" || true

    # Optionally fail the composite after upload if scan failed
    - name: Fail if scan failed
      if: ${{ always() && inputs.fail_on_scan_error == 'true' && steps.scan.outputs.exit_code != '0' }}
      shell: bash
      run: |
        echo "Aqua scan failed with exit code: ${{ steps.scan.outputs.exit_code }}"
        exit ${{ steps.scan.outputs.exit_code }}
