# name: 'Aqua Scan'
# description: 'Reusable Aqua security scan steps for workflows'
# inputs:
  # image-repo:
    # description: 'Docker image repository to scan with Aqua'
    # required: true
  # image-to-scan:
    # description: 'Docker image to scan with Aqua'
    # required: true
  # aquasec-scanner-tag:
    # description: 'Tag of the aquasec scanner to use'
    # required: true
  # aquasec-uid:
    # description: 'Aqua Security user ID'
    # required: true
  # aquasec-scanner-token:
    # description: 'Aqua Security scanner token'
    # required: true
  # aqua-trivy-exit-on-vulns:
    # description: 'Exit with error if vulnerabilities are found'
    # required: false
    # default: '1'

# runs:
  # using: "composite"

  # steps:
    # - name: Pull Aqua Scanner Image
      # run: |
        # docker pull ghcr.io/sage-erp-x3/aquasec-scanner:${{ inputs.aquasec-scanner-tag }}
      # shell: bash
    # - name: Run Aqua Security Scan
      # run: |
        # docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/aqua-scan-results:/tmp \
          # ghcr.io/sage-erp-x3/aquasec-scanner:${{ inputs.aquasec-scanner-tag }} scan \
          # --host https://${{ inputs.aquasec-uid }}.cloud.aquasec.com/ \
          # --token "${{ inputs.aquasec-scanner-token }}" \
          # --local ${{ inputs.image-repo }}/${{ inputs.image-to-scan }} \
          # --register \
          # --no-verify \
          # --registry "X3 cloud dev" \
          # --show-will-not-fix \
          # --jsonfile /tmp/out.json \
          # --htmlfile /tmp/out.html
      # shell: bash
    # - name: Check vulnerability scan results
      # run: |
        # if [ -f $(pwd)/aqua-scan-results/out.json ]; then
          # echo "Aqua Trivy scan results file found"
          # echo "Trivy scan results found, checking for vulnerabilities..."
          # trivyResults=$(jq '.vulnerability_summary.total' $(pwd)/aqua-scan-results/out.json)
          # if [ $trivyResults -gt 0 ]; then
            # echo "### Aqua Trivy scan results for ${{ inputs.image-to-scan }}" >> $GITHUB_STEP_SUMMARY
            # jq -r '[.resources[] | .vulnerabilities[]? | "\(.name): \(.description)"] | join("\n")' $(pwd)/aqua-scan-results/out.json >> $GITHUB_STEP_SUMMARY
            # echo "Vulnerabilities found in the image. Please check the Trivy scan results."
            # exit ${{ inputs.aqua-trivy-exit-on-vulns }}
          # else
            # echo "No vulnerabilities found in the image."
          # fi
        # else
          # echo "No Trivy scan results file found."
        # fi
      # shell: bash


name: "Aqua registry login + run image scanner"
description: "Logs into a private Aqua Docker registry and runs the image scanner from it"
inputs:
  registry:
    description: "Scanner Registry hostname (e.g. registry.aquasec.com)"
    required: true
  username:
    description: "Scanner Registry username"
    required: true
  password:
    description: "Scanner Registry password"
    required: true
  scanner_image:
    description: "Scanner Image name (e.g. scanner)"
    required: true
  tag:
    description: "Scanner Image tag"
    required: false
    default: "10"
  run_args:
    description: "Extra args passed to docker run (e.g. -e A=B -v ...)"
    required: false
    default: ""
  scan_args:
    description: "Command appended to docker run"
    required: false
    default: ""
  logout:
    description: "Whether to docker logout after running"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Login to registry
      uses: docker/login-action@v3
      with:
          registry: "${{ inputs.registry }}"
          username: "${{ inputs.username }}"
          password: "${{ inputs.password }}"

    - name: Pull image
      shell: bash
      run: |
        set -euo pipefail
        IMAGE="${{ inputs.registry }}/${{ inputs.scanner_image }}:${{ inputs.tag }}"
        docker pull "$IMAGE"

    - name: Run container
      shell: bash
      run: |
        set -euo pipefail
        IMAGE="${{ inputs.registry }}/${{ inputs.scanner_image }}:${{ inputs.tag }}"
        # shellcheck disable=SC2086
        docker run --rm ${{ inputs.run_args }} "$IMAGE" scan ${{ inputs.scan_args }}

    - name: Logout
      if: ${{ inputs.logout == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        docker logout "${{ inputs.registry }}" || true





    # # Scan the Image
    # - name: Run the scanner
      # run: |
        # set -euo pipefail
        # docker run --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:10 scan --host ${{ secrets.AQUA_HOST }} --local aquasupportemea/insecure-bank-app:${{ github.sha }} --token ${{ secrets.AQUA_TOKEN }} --layer-vulnerabilities --no-verify --html > .github/workflows/scan-output.html
