name: "Aqua registry login + run image scanner"
description: "Logs into private Aqua Docker registry and runs the image scanner from it"
inputs:
  registry:
    description: "Scanner Registry hostname (e.g. registry.aquasec.com)"
    required: true
  username:
    description: "Scanner Registry username"
    required: true
  password:
    description: "Scanner Registry password"
    required: true
  scanner_image:
    description: "Scanner Image name (e.g. scanner)"
    required: true
  tag:
    description: "Scanner Image tag"
    required: false
    default: "10"
  run_args:
    description: "Args passed to docker run"
    required: false
    default: ""
  scan_args:
    description: "Scan parameters"
    required: false
    default: ""
  logout:
    description: "Whether to docker logout after running"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Login to registry
      uses: docker/login-action@v3
      with:
          registry: "${{ inputs.registry }}"
          username: "${{ inputs.username }}"
          password: "${{ inputs.password }}"

    - name: Pull Scanner image
      shell: bash
      run: |
        set -euo pipefail
        IMAGE="${{ inputs.registry }}/${{ inputs.scanner_image }}:${{ inputs.tag }}"
        docker pull "$IMAGE"

    - name: Run Scanner container
      shell: bash
      run: |
        set -euo pipefail
        IMAGE="${{ inputs.registry }}/${{ inputs.scanner_image }}:${{ inputs.tag }}"
        # shellcheck disable=SC2086
        docker run --rm ${{ inputs.run_args }} "$IMAGE" scan ${{ inputs.scan_args }}

    - name: Logout from registry
      if: ${{ inputs.logout == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        docker logout "${{ inputs.registry }}" || true